import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import React from "react";

import SessionWrapperProvider from "./provider";

export const metadata: Metadata = {
  title: "t3 clone",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/dev.png" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
          <SessionWrapperProvider>{children}</SessionWrapperProvider>
      </body>
    </html>
  );
}
