import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import React from "react";

import Providers from "./providers";

export const metadata: Metadata = {
  title: "DEV.TO",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/dev-black.png" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
          <Providers>{children}</Providers>
      </body>
    </html>
  );
}
